name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: 'echo "$RCLONE_CONF" > conf'
        shell: bash
        env:
          RCONE_CONF: ${{secrets.RCLONE_CONF}}
      - uses: valeriangalliat/action-sshd-cloudflared@v1
