name: Transfer
on: 
  workflow_dispatch:     
jobs:
 rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@master
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: config show
