name: temp
on: 
  workflow_dispatch:

jobs:
 rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      - name: send 3
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: ${{ secrets.RCLONE_CONF}}
